import os
from contextlib import contextmanager
from datetime import datetime, timezone

from dateutil.relativedelta import relativedelta
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine
from sqlalchemy.exc import IntegrityError

DB_SQLITE_PATH = os.path.join(os.path.dirname(__file__), "data", "app.db")


def _database_url() -> str:
    raw = (os.getenv("DATABASE_URL") or "").strip()
    if raw:
        if raw.startswith("postgres://"):
            return raw.replace("postgres://", "postgresql+psycopg://", 1)
        if raw.startswith("postgresql://"):
            return raw.replace("postgresql://", "postgresql+psycopg://", 1)
        return raw
    os.makedirs(os.path.dirname(DB_SQLITE_PATH), exist_ok=True)
    return f"sqlite:///{DB_SQLITE_PATH.replace(os.sep, '/')}"


def get_db_backend() -> str:
    return "postgresql" if _database_url().startswith("postgresql+") else "sqlite"


def _build_engine() -> Engine:
    db_url = _database_url()
    if db_url.startswith("sqlite"):
        return create_engine(
            db_url,
            future=True,
            connect_args={"check_same_thread": False},
        )
    return create_engine(
        db_url,
        future=True,
        pool_pre_ping=True,
        pool_size=int(os.getenv("DB_POOL_SIZE", "5")),
        max_overflow=int(os.getenv("DB_MAX_OVERFLOW", "5")),
    )


engine = _build_engine()


@contextmanager
def get_db():
    conn = engine.connect()
    tx = conn.begin()
    try:
        yield conn
        tx.commit()
    except Exception:
        tx.rollback()
        raise
    finally:
        conn.close()


def init_db():
    with get_db() as conn:
        if get_db_backend() == "sqlite":
            user_table_sql = """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    email VARCHAR(255) UNIQUE NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    is_vip INTEGER DEFAULT 0,
                    vip_expire_at VARCHAR(64),
                    daily_summary_count INTEGER DEFAULT 0,
                    last_summary_date VARCHAR(32),
                    ab_user_id INTEGER UNIQUE,
                    created_at VARCHAR(64),
                    updated_at VARCHAR(64)
                )
            """
            order_table_sql = """
                CREATE TABLE IF NOT EXISTS orders (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    order_no VARCHAR(80) UNIQUE NOT NULL,
                    user_id INTEGER NOT NULL,
                    amount INTEGER NOT NULL,
                    currency VARCHAR(16) DEFAULT 'cny',
                    status VARCHAR(32) DEFAULT 'pending',
                    plan_type VARCHAR(32) DEFAULT 'monthly',
                    stripe_session_id VARCHAR(255) UNIQUE,
                    stripe_payment_intent_id VARCHAR(255),
                    paid_at VARCHAR(64),
                    created_at VARCHAR(64),
                    updated_at VARCHAR(64)
                )
            """
        else:
            user_table_sql = """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email VARCHAR(255) UNIQUE NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    is_vip INTEGER DEFAULT 0,
                    vip_expire_at VARCHAR(64),
                    daily_summary_count INTEGER DEFAULT 0,
                    last_summary_date VARCHAR(32),
                    ab_user_id INTEGER UNIQUE,
                    created_at VARCHAR(64),
                    updated_at VARCHAR(64)
                )
            """
            order_table_sql = """
                CREATE TABLE IF NOT EXISTS orders (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_no VARCHAR(80) UNIQUE NOT NULL,
                    user_id INTEGER NOT NULL,
                    amount INTEGER NOT NULL,
                    currency VARCHAR(16) DEFAULT 'cny',
                    status VARCHAR(32) DEFAULT 'pending',
                    plan_type VARCHAR(32) DEFAULT 'monthly',
                    stripe_session_id VARCHAR(255) UNIQUE,
                    stripe_payment_intent_id VARCHAR(255),
                    paid_at VARCHAR(64),
                    created_at VARCHAR(64),
                    updated_at VARCHAR(64)
                )
            """

        conn.execute(text(user_table_sql))
        conn.execute(text(order_table_sql))
        conn.execute(text("CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS idx_orders_order_no ON orders(order_no)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS idx_orders_stripe_session_id ON orders(stripe_session_id)"))
        _ensure_user_sync_schema(conn)


def _ensure_user_sync_schema(conn) -> None:
    cols = conn.execute(text("SELECT * FROM users LIMIT 0")).keys()
    if "ab_user_id" not in cols:
        conn.execute(text("ALTER TABLE users ADD COLUMN ab_user_id INTEGER"))
        conn.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS idx_users_ab_user_id ON users(ab_user_id)"))


def _to_vip_expire(value: str | None) -> str | None:
    if not value:
        return None
    s = str(value).strip()
    if not s:
        return None
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(s)
    except ValueError:
        return None
    return dt.isoformat()


def _row_to_dict(row) -> dict:
    return dict(row._mapping) if row else {}


FREE_DAILY_SUMMARY_LIMIT = 3


def get_user_by_email(email: str) -> dict | None:
    with get_db() as conn:
        row = conn.execute(text("SELECT * FROM users WHERE email = :email"), {"email": email}).fetchone()
        return _row_to_dict(row) if row else None


def get_user_by_id(user_id: int) -> dict | None:
    with get_db() as conn:
        row = conn.execute(text("SELECT * FROM users WHERE id = :uid"), {"uid": user_id}).fetchone()
        return _row_to_dict(row) if row else None


def sync_user_from_ab(ab_user: dict) -> dict:
    ab_uid_raw = ab_user.get("id")
    try:
        ab_uid = int(ab_uid_raw) if ab_uid_raw is not None else None
    except (TypeError, ValueError):
        ab_uid = None

    email = (ab_user.get("email") or "").strip()
    if not email:
        suffix = str(ab_uid) if ab_uid is not None else "unknown"
        email = f"ab_{suffix}@local.invalid"

    is_vip = 1 if bool(ab_user.get("is_vip")) else 0
    vip_expire = _to_vip_expire(ab_user.get("membership_until") or ab_user.get("vip_expire_at"))
    now = datetime.now(timezone.utc).isoformat()

    with get_db() as conn:
        user_row = None
        if ab_uid is not None:
            user_row = conn.execute(
                text("SELECT * FROM users WHERE ab_user_id = :ab_uid"),
                {"ab_uid": ab_uid},
            ).fetchone()
        if not user_row:
            user_row = conn.execute(
                text("SELECT * FROM users WHERE email = :email"),
                {"email": email},
            ).fetchone()

        if user_row:
            conn.execute(
                text(
                    """
                    UPDATE users
                    SET email = :email, is_vip = :is_vip, vip_expire_at = :vip_expire_at,
                        ab_user_id = :ab_user_id, updated_at = :updated_at
                    WHERE id = :uid
                    """
                ),
                {
                    "email": email,
                    "is_vip": is_vip,
                    "vip_expire_at": vip_expire,
                    "ab_user_id": ab_uid,
                    "updated_at": now,
                    "uid": int(user_row._mapping["id"]),
                },
            )
        else:
            conn.execute(
                text(
                    """
                    INSERT INTO users (
                        email, password_hash, is_vip, vip_expire_at, ab_user_id, created_at, updated_at
                    ) VALUES (
                        :email, :password_hash, :is_vip, :vip_expire_at, :ab_user_id, :created_at, :updated_at
                    )
                    """
                ),
                {
                    "email": email,
                    "password_hash": "__ab_sso__",
                    "is_vip": is_vip,
                    "vip_expire_at": vip_expire,
                    "ab_user_id": ab_uid,
                    "created_at": now,
                    "updated_at": now,
                },
            )

        fresh = conn.execute(text("SELECT * FROM users WHERE email = :email"), {"email": email}).fetchone()
        return _row_to_dict(fresh) if fresh else {"email": email, "is_vip": bool(is_vip)}


def create_user(email: str, password_hash: str) -> dict:
    now = datetime.now(timezone.utc).isoformat()
    with get_db() as conn:
        try:
            conn.execute(
                text(
                    """
                    INSERT INTO users (email, password_hash, created_at, updated_at)
                    VALUES (:email, :password_hash, :created_at, :updated_at)
                    """
                ),
                {"email": email, "password_hash": password_hash, "created_at": now, "updated_at": now},
            )
        except IntegrityError:
            row = conn.execute(text("SELECT id, email FROM users WHERE email = :email"), {"email": email}).fetchone()
            if row:
                m = row._mapping
                return {"id": m["id"], "email": m["email"]}
            raise
        row = conn.execute(text("SELECT id, email FROM users WHERE email = :email"), {"email": email}).fetchone()
        m = row._mapping
        return {"id": m["id"], "email": m["email"]}


def peek_summary_eligibility(user_id: int) -> tuple[bool, str | None, bool]:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    user = get_user_by_id(user_id)
    if not user:
        return False, "账户数据异常，请重新登录", False

    if user.get("is_vip") and user.get("vip_expire_at"):
        try:
            expire = datetime.fromisoformat(str(user["vip_expire_at"]))
            if expire > datetime.now(timezone.utc):
                return True, None, False
        except (ValueError, TypeError):
            pass

    if user.get("last_summary_date") != today:
        return True, None, False

    current = int(user.get("daily_summary_count") or 0)
    if current >= FREE_DAILY_SUMMARY_LIMIT:
        return False, "今日AI总结次数已用完", True
    return True, None, False


def consume_summary_quota(user_id: int) -> int:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    now = datetime.now(timezone.utc).isoformat()
    with get_db() as conn:
        row = conn.execute(text("SELECT * FROM users WHERE id = :uid"), {"uid": user_id}).fetchone()
        if not row:
            return 0
        user = row._mapping

        if user.get("is_vip") and user.get("vip_expire_at"):
            try:
                expire = datetime.fromisoformat(str(user["vip_expire_at"]))
                if expire > datetime.now(timezone.utc):
                    return -1
            except (ValueError, TypeError):
                pass

        if user.get("last_summary_date") != today:
            conn.execute(
                text(
                    """
                    UPDATE users
                    SET daily_summary_count = 1, last_summary_date = :today, updated_at = :updated_at
                    WHERE id = :uid
                    """
                ),
                {"today": today, "updated_at": now, "uid": user_id},
            )
            return FREE_DAILY_SUMMARY_LIMIT - 1

        conn.execute(
            text(
                """
                UPDATE users
                SET daily_summary_count = COALESCE(daily_summary_count, 0) + 1, updated_at = :updated_at
                WHERE id = :uid
                """
            ),
            {"updated_at": now, "uid": user_id},
        )
        updated = conn.execute(
            text("SELECT daily_summary_count FROM users WHERE id = :uid"),
            {"uid": user_id},
        ).fetchone()
        cnt = int(updated._mapping["daily_summary_count"]) if updated else 0
        return max(0, FREE_DAILY_SUMMARY_LIMIT - cnt)


def create_order(user_id: int, order_no: str, amount: int, currency: str = "cny", plan_type: str = "monthly") -> dict:
    now = datetime.now(timezone.utc).isoformat()
    with get_db() as conn:
        conn.execute(
            text(
                """
                INSERT INTO orders (
                    order_no, user_id, amount, currency, plan_type, created_at, updated_at
                ) VALUES (
                    :order_no, :user_id, :amount, :currency, :plan_type, :created_at, :updated_at
                )
                """
            ),
            {
                "order_no": order_no,
                "user_id": user_id,
                "amount": amount,
                "currency": currency,
                "plan_type": plan_type,
                "created_at": now,
                "updated_at": now,
            },
        )
        return {"order_no": order_no, "user_id": user_id, "amount": amount}


def update_order_stripe_session(order_no: str, session_id: str):
    with get_db() as conn:
        conn.execute(
            text(
                """
                UPDATE orders
                SET stripe_session_id = :session_id, updated_at = :updated_at
                WHERE order_no = :order_no
                """
            ),
            {
                "session_id": session_id,
                "updated_at": datetime.now(timezone.utc).isoformat(),
                "order_no": order_no,
            },
        )


def complete_order(session_id: str, payment_intent_id: str) -> dict | None:
    with get_db() as conn:
        order_row = conn.execute(
            text("SELECT * FROM orders WHERE stripe_session_id = :sid AND status = 'pending'"),
            {"sid": session_id},
        ).fetchone()
        if not order_row:
            return None
        order = order_row._mapping
        now = datetime.now(timezone.utc).isoformat()

        user_row = conn.execute(text("SELECT * FROM users WHERE id = :uid"), {"uid": order["user_id"]}).fetchone()
        if not user_row:
            return None
        user = user_row._mapping

        current_expire = None
        if user.get("vip_expire_at"):
            try:
                current_expire = datetime.fromisoformat(str(user["vip_expire_at"]))
            except ValueError:
                pass

        base_time = datetime.now(timezone.utc)
        if current_expire and current_expire > base_time:
            base_time = current_expire

        if order["plan_type"] == "yearly":
            new_expire = base_time + relativedelta(years=1)
        else:
            new_expire = base_time + relativedelta(months=1)

        conn.execute(
            text(
                """
                UPDATE orders
                SET status = 'paid', stripe_payment_intent_id = :piid, paid_at = :paid_at, updated_at = :updated_at
                WHERE id = :oid
                """
            ),
            {
                "piid": payment_intent_id,
                "paid_at": now,
                "updated_at": now,
                "oid": order["id"],
            },
        )
        conn.execute(
            text(
                """
                UPDATE users
                SET is_vip = 1, vip_expire_at = :vip_expire_at, updated_at = :updated_at
                WHERE id = :uid
                """
            ),
            {
                "vip_expire_at": new_expire.isoformat(),
                "updated_at": now,
                "uid": order["user_id"],
            },
        )
        return dict(order)


def get_order_by_no(order_no: str) -> dict | None:
    with get_db() as conn:
        row = conn.execute(text("SELECT * FROM orders WHERE order_no = :order_no"), {"order_no": order_no}).fetchone()
        return _row_to_dict(row) if row else None


def get_user_orders(user_id: int) -> list[dict]:
    with get_db() as conn:
        rows = conn.execute(
            text("SELECT * FROM orders WHERE user_id = :uid ORDER BY created_at DESC"),
            {"uid": user_id},
        ).fetchall()
        return [dict(r._mapping) for r in rows]
